language: python

before_install:
  - sudo apt-get install graphviz
  - mkdir output

script:
  - for file in $(ls *.dot) ; do dot "${file}" -Tpng -Nfontname="Open Sans" -Efontname="Open Sans" -Gfontname="Open Sans" -o output/"${file%.*}".png ; done

deploy:
  provider: pages
  local-dir: output
  target-branch: artifacts
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
